// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPages.Contexts;

#nullable disable

namespace RazorPages.Migrations
{
    [DbContext(typeof(BackeryContext))]
    [Migration("20240729163246_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorPages.Models.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageFileName");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("9c2adeab-ef8b-4d3c-812e-f08b826a84e5"),
                            Description = "A scrumptious carrot cake encrusted with sliced almonds",
                            ImageName = "carrot-cake.jpg",
                            Price = 150.09999999999999,
                            ProductName = "Carrot Cake"
                        },
                        new
                        {
                            ID = new Guid("b23903e6-d6f0-4eb6-bba6-9a6f7e03e7d4"),
                            Description = "A delicious lemon tart smothered with juicy fresh fruit",
                            ImageName = "lemon-tart.jpg",
                            Price = 20.0,
                            ProductName = "Lemon Tart"
                        },
                        new
                        {
                            ID = new Guid("f3fa39bb-3ccb-4baa-9591-b3abb01e9e83"),
                            Description = "Delectable vanilla and chocolate cupcakes",
                            ImageName = "cup-cakes.jpg",
                            Price = 7.5,
                            ProductName = "Cupcakes"
                        },
                        new
                        {
                            ID = new Guid("9faf6ece-e557-4cb3-bfa9-311de2c0990c"),
                            Description = "Fresh baked French-style bread, bagettes and cobs",
                            ImageName = "bread.jpg",
                            Price = 18.0,
                            ProductName = "Bread"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
