-- Triggers
-- =============
-- A trigger is a database object that runs automatically when an event occurs. 
-- DML Triggers
-- DML Triggers are fired when a DML event occures. i.e. when data is inserted/update/delete etc
